#源数据
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT&useSSL=FALSE&allowPublicKeyRetrieval=true
  username: root
#  password: Waqq1230.0
  password: wrial.qq.com
# 按ctrl + f9
 thymeleaf:
  cache: false